### ISSUE TITLE
HEJ OLA

### ISSUE THREAD

**Issue by ag1zywert** [AleksandraZamarja/melon#2]
Hej Ola!
Jak się **bawicie**?
Widzę, że przednio!!!!!!
Pozdrowionka

**Comment by AleksandraZamarja** [comment]
Witaj Agatka!
Bawie się niesamwicie dobrze, dawno tak się dobrze nie bawiłam
Czuję się programistą :) 
a co tam ?

**Comment by ag1zywert** [comment]
A wszystko spoko, siedzę w domu i bardzo żałuję, że omija mnie taka wspaniała rozrywka.
Żartuję, tak naprawdę w domu też jest _klawo_
Może w przyszłości zaprogramujesz jakiś program do obliczania wyników PTS albo NEO FFI jak mąż grubej :) 
xoxo

**Comment by AleksandraZamarja** [comment]
Słuchaj juz jestem w trakcie programowania programu do obliczania wyników MMPI, jakbyś chciała to udostępnię Ci :) 
xoxo

**Comment by ag1zywert** [comment]
Oh dziękuję! Tylko nie wiem czy jestem tego godna :/ Bardzo możliwe, że nie bo nasze _case study_ odbiegało od ideału... Ponadto z tego co mówił dziadek z Kanady **MMPI** ssie, więc nie jestem pewna czy to działanie ma sens. 
z mocą pozdrowień
ja

**Comment by AleksandraZamarja** [comment]
Kurcze, w takim razie wyjeżdżam i stworzę własny test po czym stworzę program. Daj mi rok, a powrócę.
Z wyrazami szacunku,
me

**Comment by ag1zywert** [comment]
Okej, trzymam kciuki i mam nadzieję, że wielki świat Cię nie pochłonie
_bez odbioru_
tajemniczy wielbiciel

**Comment by AleksandraZamarja** [comment]
a prezentacja sie nie przejmuj, oni się nie znajo.
xoxo,
żegnaj
